### ISSUE TITLE
iondide-fsharp 1.4.1 not working

### ISSUE THREAD

**Issue by digiorgi** [ionide/ionide-fsharp#172] opened 2015-10-24 02:07 UTC
I just updated to 1.4.1 and now the auto-completion, errors, suggestions, or anything related to ionide-sharp works.

(:

**Comment by Krzysztof-Cieslak** [comment] 2015-10-24 10:00
Have you used `1.4.0` or have you upgraded from earlier version? It might be connected with #169

**Comment by digiorgi** [comment] 2015-10-24 12:19
Ohoo. I just tested and the versions 1.4.1 and 1.4.0 don't work. What works for me is v1.3.3. I'm using ubuntu totally updated with F# 4.0 opensource edition. What should i do to make it work on linux?

**Comment by rmunn** [comment] 2015-10-25 15:12
I'm also having problems running on Linux, and I found what might be the cause, or part of the cause. In `${HOME}/.atom/nohup.out`, I see the following error:

> [9446:1025/155145:INFO:CONSOLE(2693)] "Cannot open assembly '/home/rmunn/.atom/packages/ionide-fsharp/bin/fsautocomplete.suave.exe': No such file or directory.
", source: /home/rmunn/.atom/packages/ionide-fsharp/lib/fsharp.js (2693)

The file in `/home/rmunn/.atom/packages/ionide-fsharp/bin/` is named FsAutoComplete.Suave.exe, not fsautocomplete.suave.exe. The incorrect capitalization won't cause any problems on Windows, but on Linux it's not finding the right file for the autocomplete feature -- and, since I don't have anything else (errors, suggestions, etc) working either, I suspect the filenames might be incorrectly cased there, too.

**Comment by rmunn** [comment] 2015-10-25 15:17
That filename is coming from:

https://github.com/ionide/ionide-fsharp/blob/d6a0c74caba79b78507ce3408ca7b40a79a36a4b/src/Core/LanguageService.fs#L138

Also, https://github.com/ionide/ionide-fsharp/blob/60a1266a929ee14419bbd50a3dcdc0897922e750/src/Components/Format.fs#L19 is going to fail, too: it wants a file named `fantomas.exe` but the one in `ionide-fsharp/bin-fantomas` is named `Fantomas.exe`.

**Comment by Krzysztof-Cieslak** [comment] 2015-10-25 19:41
Should be fixed in `1.4.2`

**Closed by Krzysztof-Cieslak** 2015-10-25 19:41 UTC

**Comment by digiorgi** [comment] 2015-10-26 13:10
Yes. Is fixed in 1.4.2. Thanks!
