### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by 7sharp9** [ionide/ionide-fsharp#43] opened 2015-05-15 08:30 UTC
[Enter steps to reproduce below:]

1. Disable plugin

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [FSharp](https://github.com/fsprojects/FSharp.Atom) package, v0.1.14

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:275:12)
  at /Users/dave/.atom/packages/FSharp/lib/fsharp.js:962:18
  at Option__Iterate$ChildProcess_ChildProcess_ (/Users/dave/.atom/packages/FSharp/lib/fsharp.js:1273:14)
  at LanguageService__ask$ (/Users/dave/.atom/packages/FSharp/lib/fsharp.js:941:5)
  at LanguageService__parse$ (/Users/dave/.atom/packages/FSharp/lib/fsharp.js:1012:12)
  at LanguageService__parseEditor$ (/Users/dave/.atom/packages/FSharp/lib/fsharp.js:1052:14)
  at /Users/dave/.atom/packages/FSharp/lib/fsharp.js:845:22
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:292:19)
  at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:263:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:372:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:442:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:183:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "autocomplete",
      "FSharp"
    ],
    "themes": [
      "atom-dark-ui",
      "cobalt"
    ]
  }
}
```

### Installed Packages

```coffee
# User
cobalt, v0.5.0
color-picker, v1.7.0
highlight-selected, v0.9.3
language-csharp, v0.5.0
language-fsharp, v0.8.4
select-rectangle, v1.0.2

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment] 2015-05-15 11:57
Should be fixed in `0.1.15`

**Comment by adamchester** [comment] 2015-05-20 11:57
Same error here, on Windows 10 ?

**Atom Version**: 0.200.0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [FSharp](https://github.com/fsprojects/FSharp.Atom) package, v0.2.8

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:275:12)
    at C:\Users\adamchester\.atom\packages\FSharp\lib\fsharp.js:980:18
    at Option__Iterate$ChildProcess_ChildProcess_ (C:\Users\adamchester\.atom\packages\FSharp\lib\fsharp.js:1311:14)
    at LanguageService__ask$ (C:\Users\adamchester\.atom\packages\FSharp\lib\fsharp.js:960:12)
    at LanguageService__tooltip$ (C:\Users\adamchester\.atom\packages\FSharp\lib\fsharp.js:1136:12)
    at C:\Users\adamchester\.atom\packages\FSharp\lib\fsharp.js:2486:30
```

### Commands

```
  2x -1:30.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-sharp"
    ]
  }
}
```

### Installed Packages

```coffee
# User
FSharp, v0.2.8
language-fsharp, v0.8.4

# Dev
No dev packages
```

**Comment by Bomret** [comment] 2015-05-29 19:48
Same problem on a fresh install of Atom on Windows 10 Build 10074.

**Atom Version**: 0.204.0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [FSharp](https://github.com/fsprojects/FSharp.Atom) package, v0.4.1


### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:275:12)
  at C:\Users\publi\.atom\packages\FSharp\lib\fsharp.js:1107:25
  at Option__Iterate$ChildProcess_ChildProcess_ (C:\Users\publi\.atom\packages\FSharp\lib\fsharp.js:1515:14)
  at LanguageService__ask$ (C:\Users\publi\.atom\packages\FSharp\lib\fsharp.js:1105:12)
  at LanguageService__parse$ (C:\Users\publi\.atom\packages\FSharp\lib\fsharp.js:1159:12)
  at LanguageService__parseEditor$ (C:\Users\publi\.atom\packages\FSharp\lib\fsharp.js:1167:14)
  at C:\Users\publi\.atom\packages\FSharp\lib\fsharp.js:1743:16
  at Emitter.module.exports.Emitter.emit (C:\Users\publi\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\publi\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1219:25

```

### Commands

```
     -0:03.1.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
FSharp, v0.4.1

# Dev
No dev packages
```

**Comment by CumpsD** [comment] 2015-06-11 08:12
Happened to me today as well, on 0.5.0

**Atom Version**: 0.207.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.5.0


### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:275:12)
  at C:\Touchy\Development\Atom\home\packages\atom-fsharp\lib\fsharp.js:1540:25
  at Option__Iterate$ChildProcess_ChildProcess_ (C:\Touchy\Development\Atom\home\packages\atom-fsharp\lib\fsharp.js:2026:14)
  at LanguageService__ask$ (C:\Touchy\Development\Atom\home\packages\atom-fsharp\lib\fsharp.js:1538:12)
  at LanguageService__tooltip$ (C:\Touchy\Development\Atom\home\packages\atom-fsharp\lib\fsharp.js:1770:12)
  at C:\Touchy\Development\Atom\home\packages\atom-fsharp\lib\fsharp.js:3767:22

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "project-colorize",
      "autocomplete"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.5.0
atom-jade, v0.3.0
file-icons, v1.5.7
jshint, v1.3.7
language-fsharp, v0.8.4
Paket, v1.0.0
react, v0.12.0

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment] 2015-06-23 15:45
I think that it's connected with https://github.com/fsharp/FsAutoComplete/issues/28

**Comment by sergey-tihon** [comment] 2015-06-23 18:56
The same issue with `atom-fsharp, v0.6.0`.
```
Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:275:12)
  at C:\Users\Siarhei_Tsikhan\.atom\packages\atom-fsharp\lib\fsharp.js:1615:25
  at Option__Iterate$ChildProcess_ChildProcess_ (C:\Users\Siarhei_Tsikhan\.atom\packages\atom-fsharp\lib\fsharp.js:2204:14)
  at LanguageService__ask$ (C:\Users\Siarhei_Tsikhan\.atom\packages\atom-fsharp\lib\fsharp.js:1613:12)
  at LanguageService__tooltip$ (C:\Users\Siarhei_Tsikhan\.atom\packages\atom-fsharp\lib\fsharp.js:1867:12)
  at C:\Users\Siarhei_Tsikhan\.atom\packages\atom-fsharp\lib\fsharp.js:4573:22
```

![image](https://cloud.githubusercontent.com/assets/1197905/8314466/68d15046-19f2-11e5-80e7-480992035203.png)

**Comment by clausasbjorn** [comment] 2015-07-05 11:08
I am experiencing the same issue when trying to load up a script-based application (https://github.com/clausasbjorn/suave-todo).

**Steps**

1. Fresh install of Atom 1.0.0
2. Install atom-fsharp 0.7.2
3. Install linter 1.1.0
4. Open folder "suave-todo"

No problems when creating a new folder and adding scripts to it. Also no problems with existing F# projects.

**Error 1**
```
    Error: This socket has been ended by the other party
      at Socket.writeAfterFIN [as write] (net.js:275:12)
      at C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:1866:25
      at Option__Iterate$ChildProcess_ChildProcess_ (C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:2621:14)
      at LanguageService__ask$ (C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:1864:12)
      at LanguageService__tooltip$ (C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:2160:12)
      at C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:5176:22
```

![image](https://cloud.githubusercontent.com/assets/91872/8511437/3c53654a-2316-11e5-9ed7-b9749794163c.png)

**Error 2**
```
Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:275:12)
  at C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:1866:25
  at Option__Iterate$ChildProcess_ChildProcess_ (C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:2621:14)
  at LanguageService__ask$ (C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:1864:12)
  at LanguageService__parse$ (C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:1931:12)
  at LanguageService__parseEditor$ (C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:1939:14)
  at C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:596:14
  at ErrorLinterProvider__lint$ (C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:597:7)
  at ErrorLinterProvider__lint$ (C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:585:12)
  at [object Object].lint (C:\Users\Claus\.atom\packages\atom-fsharp\lib\fsharp.js:579:14)
  at C:\Users\Claus\.atom\packages\linter\lib\editor-linter.coffee:85:24
  at C:\Users\Claus\.atom\packages\linter\lib\editor-linter.coffee:84:25
  at Set.forEach (native)
  at EditorLinter.triggerLinters (C:\Users\Claus\.atom\packages\linter\lib\editor-linter.coffee:78:26)
  at EditorLinter.lint (C:\Users\Claus\.atom\packages\linter\lib\editor-linter.coffee:72:18)
  at C:\Users\Claus\.atom\packages\linter\lib\editor-linter.coffee:26:37
  at Emitter.module.exports.Emitter.emit (C:\Users\Claus\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Claus\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1183:25
```

![image](https://cloud.githubusercontent.com/assets/91872/8511439/49a16df0-2316-11e5-8eef-529ed9a44589.png)

**Comment by adamchester** [comment] 2015-07-05 12:08
I think there are potentially multiple reasons for this. In my case, it's often due to [FSAC crashing when it can't find the newer FSharp](fsharp/FsAutoComplete#25).

Try watching what commands are sent to FSAC, then perform them manually, and see you can get any more info if FSAC crashes.

**Comment by clausasbjorn** [comment] 2015-07-06 13:23
Thanks @adamchester for pointing me in the direction of FsAutoComplete. I've been experimenting a bit, and it looks like FSAC is the cause of the problem. What usually happens is that the "tooltip" command causes FSAC to malfunction.

I couldn't really see a pattern between failures and size of project or project references.

I've tried attaching a debugger to the FsAutoComplete process and it seems my problems occur in LanguageService.fs l:299:

```
let opts =
    Async.RunSynchronously (checker.GetProjectOptionsFromScript(fileName, source, fakeDateTimeRepresentingTimeLoaded projFilename),
    timeout = ServiceSettings.maximumTimeout)
````

It fails because of a timeout while executing 

```
checker.GetProjectOptionsFromScript(fileName, source, fakeDateTimeRepresentingTimeLoaded projFilename)
```

I've tried compiling a new version with a larger timeout (default ServiceSettings.maximumTimeout is 5000ms), and that actually seems to solve the problem for me.

I've fetched the FSharp.Compiler.Services project containing GetProjectOptionsFromScript, but haven't had a chance to see if I can figure out why it needs 5+ seconds to execute.

**Comment by 7sharp9** [comment] 2015-07-06 13:32
Do you have lots of #load commands?

**Comment by clausasbjorn** [comment] 2015-07-06 13:51
@7sharp9 .. Well, not a lot really. The "header" of the script that consistently causes problems looks like this.

```
#r "packages/Suave/lib/net40/Suave.dll"
#r "System.Data.dll"
#r "System.Data.Linq.dll"
#r "FSharp.Data.TypeProviders.dll"
#load "static.fsx"
```

**Comment by tpetricek** [comment] 2015-07-06 14:25
I get this quite often and I have lots of `#load` commands: https://github.com/tpetricek/FsSnip.Website/blob/master/app.fsx#L23

Is this caused by the timeout in the FsAutocomplete service?

**Comment by CumpsD** [comment] 2015-07-06 14:31
I had this with 0 loads.

**Comment by 7sharp9** [comment] 2015-07-06 14:35
I guess if you the timeout then you have an exception condition, the very first iteration can be very slow, easily 3-4 seconds.  If you request checking option for project files I would expect it to take several seconds too.  I use an MRU cache in XS with is evicted on the fsproj changing.  Script checker closures are cached though although it doesn't seem to improve thins a great deal.

**Comment by 7sharp9** [comment] 2015-07-06 14:38
Note there are two environmental variable which can be set:

`FSharpBinding_BlockingTimeout` default is 250
`FSharpBinding_MaxTimeout` default is 5000

**Comment by tpetricek** [comment] 2015-07-06 15:00
I just don't see why there should be _any_ timeout when starting the application.

**Comment by 7sharp9** [comment] 2015-07-06 15:02
If its not ngen'ed then there will be at least a big chunk of jit up front before anything runs.  FSC has a very slow start up.

**Comment by koenmetsu** [comment] 2015-07-09 10:48
>Note there are two environmental variable which can be set:
>
>FSharpBinding_BlockingTimeout default is 250
>FSharpBinding_MaxTimeout default is 5000

@7sharp9 I set the 2 env variables to respectively 5000 and 1000, haven't seen an improvement.

NB: the atom-fsharp is working fine on my other machine.

**Comment by rneatherway** [comment] 2015-07-14 10:14
Everyone who has experienced this, which platform are you using?

@tpetricek: this function has to be called every time a script is parsed in case it depends on some new assemblies or other script files. If it didn't have a timeout then it could lock up FsAutoComplete.

**Comment by CumpsD** [comment] 2015-07-14 10:31
Win8.1 here

**Comment by 7sharp9** [comment] 2015-07-14 12:40
@koenmetsu You probably want to set the `FSharpBinding_MaxTimeout` higher, I think that ones used for the type checking/parse, the `FSharpBinding_BlockingTimeout is used during tooltips and completion functions.

**Comment by rneatherway** [comment] 2015-07-14 13:26
I am working on fixing this in FsAutoComplete so that it doesn't crash, just returns no results and lets you try again. It's requiring some refactoring, but hopefully this week there should be a new release.

**Comment by clausasbjorn** [comment] 2015-07-14 19:27
@rneatherway Win 8.1 here as well. Thank you for looking into it!

**Comment by koenmetsu** [comment] 2015-07-15 15:30
@rneatherway 8.1 as well

**Comment by koenmetsu** [comment] 2015-07-15 15:30
@7sharp9 define higher?

**Comment by rneatherway** [comment] 2015-07-15 15:40
Try setting it to 30000

**Comment by koenmetsu** [comment] 2015-07-16 08:16
@rneatherway also win7 enterprise

**Comment by rneatherway** [comment] 2015-07-28 17:10
This should be fixed by updating atom to use the new release: https://github.com/fsharp/FsAutoComplete/releases/tag/0.20.0

**Comment by tpetricek** [comment] 2015-07-28 22:24
Fantastic, @rneatherway thanks for all the hard work on this. I can't wait for a new Atom package :-P

**Comment by Krzysztof-Cieslak** [comment] 2015-07-28 22:27
@tpetricek, don't count your chickens before they're hatched, we have some minor problems with released version... sound typical for .Net environment ;)

**Comment by tpetricek** [comment] 2015-07-28 22:36
:-D is it crashing the JIT, or does it have wrong icon?

**Comment by Krzysztof-Cieslak** [comment] 2015-07-28 22:43
More or less looks like JIT crashing ;P

**Comment by larsw** [comment] 2015-07-31 08:52
Hi, I'm experiencing this problem even if I updated FsAutocomplete. (Win10-x64, VS2015/.NET 4.6/F# 4.0)

**Comment by Krzysztof-Cieslak** [comment] 2015-07-31 08:59
@larsw 
Hi :),
1. Released version of atom-fsharp is not compatible with newest FSAC yet - I'll push update later today.
2. There was minor FSAC release yesterday with some bug fixes.
3. To get working FSAC working on Win 10 / F# 4.0 / VS 2015, you need to install additional things - described in requirements section in readme of FSAC repository.

**Comment by larsw** [comment] 2015-07-31 09:47
Ok, thanks for the quick response :)

**Comment by larsw** [comment] 2015-08-03 18:18
@Krzysztof-Cieslak maybe I'm daft, but re. your answer no. 3 above, I can't really find anything about it here: https://github.com/fsharp/FsAutoComplete

**Comment by rneatherway** [comment] 2015-08-03 18:27
It's under 'required software'.
https://github.com/fsharp/FsAutoComplete/blob/master/README.md#required-software

**Comment by larsw** [comment] 2015-08-04 06:12
Well, in 3. above, you wrote "To get working FSAC working on Win 10 / F# 4.0 / VS 2015 ...", but the stuff mentioned under Required software is F# 3.1 and 2013 build tools, so there was a slight ambiguity there :-P

**Comment by rneatherway** [comment] 2015-08-04 09:01
Right, that's true. I'm not sure of a neater way of phrasing it though. FSAC only supports F# 3.1 at the moment, but the new release (next few days) will support F# 4.0. It will still require the 2013 build tools though for parsing `.fsproj` files.

**Comment by Krzysztof-Cieslak** [comment] 2015-08-04 10:51
Plugin update to use FSAC 0.21.0, so hopefully this error will no occur anymore.

**Comment by larsw** [comment] 2015-08-04 11:10
@rneatherway out of curiousity; where in the atom-fsharp code is the build tools used to parse the fsproj files? Would a PR with a reimplementation of just the necessary functionality be interesting (to get rid of the dependency) ?

**Comment by Krzysztof-Cieslak** [comment] 2015-08-04 11:11
@larsw: It's not part of atom-fsharp but FsAutoComplete. atom-fsharp just send request to FSAC to parse project file.

**Comment by rneatherway** [comment] 2015-08-04 11:31
@larsw: unfortunately it is an extremely non-trivial process. We don't just need to parse the XML, but to determine the exact compiler arguments that will be used in compilation (this is why we use MSBuild), because these have to be passed into the compiler services to get completion information etc in the right context.

**Comment by rneatherway** [comment] 2015-08-04 11:32
PS. It is an aim to make FCS just use whatever version of MSBuild it can find on the host machine, but that is still ongoing. At the moment it requires MSBuild 12 exactly.

**Comment by larsw** [comment] 2015-08-04 11:50
@rneatherway ok, thanks for the feedback.

**Comment by zhengbli** [comment] 2015-08-25 20:51
In my case, I have the issue when I open both VS and Atom at the same time, with F# interactive console open in VS. The issue goes away after I closed VS.

**Comment by zhengbli** [comment] 2015-09-20 18:43
FYI I still have this problem frequently on a clean install using ionide installer (clean atom, no other plugins)

**Comment by photex** [comment] 2015-09-20 18:57
Unable to open any fsharp files with ionide because of this issue. Clean ATOM install. VS is not open.

**Comment by Krzysztof-Cieslak** [comment] 2015-09-20 19:17
@zhengbli @photex Do You get this right on start? 
If so please ensure if file `C:\Users\USERNAME\.atom\packages\ionide-fsharp\bin\fsautocomplete.exe` exists. If no please reinstall `ionide-fsharp` plugin - sometimes Atom has problems with downloading new packages (actually that might be good try even if file exist)

**Comment by zhengbli** [comment] 2015-09-20 19:26
@Krzysztof-Cieslak  I do have the ``fsautocomplete.exe``. I found it mostly occurs when I have a fsi REPL open in atom, then close and reopen ATOM with the REPL window there. I tried reinstall everything (deleted the whole .atom folder also), the situation remains the same.

**Comment by photex** [comment] 2015-09-22 19:04
@Krzysztof-Cieslak I removed ~/.atom and let ionide-installer do it's thing, then restarted atom. Haven't had this issue yet since.

**Comment by Krzysztof-Cieslak** [comment] 2015-09-22 19:33
@photex, Glad it's working :) Hope You'll like Ionide

**Comment by zhengbli** [comment] 2015-09-22 23:48
I found a possible cause for my case. I set the language type of the fsi window to be "F#" instead of "Plain text", and once I set it back the issue disappears.

**Closed** 2015-09-29 16:42 UTC
Labels: bug
